[package]
name = "rdiff"
version = "0.1.0"
authors = ["Justin Barclay <justincbarclay@gmail.com>"]
edition = "2018"

[[bin]]
name = "rdiff"
path = "src/main.rs"

[dependencies]
clap = "2.32.0"
time = "0.2"