[package]
name = "rdiff"
version = "0.1.0"
authors = ["Justin Barclay <justincbarclay@gmail.com>"]

[lib]
name = "diff"
path = "src/lib/diff/diff.rs"

[[bin]]
name = "rdiff"
path = "src/main.rs"

[dependencies]
clap = "2.32.0"
time = "0.1"